language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

matrix:
  include:
    - env: NAME='Examples test' TASK='examples_full_test' SHOULD_BUILD_DOCS=0
    - env: NAME='Snippets test' TASK='snippets_full_test' SHOULD_BUILD_DOCS=1

before_install:
  - chmod +x gradlew

install:
  - sudo apt-get install nodejs npm
  - npm config set strict-ssl false
  - npm install chalk fancy-log simple-git

before_script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}"  > ~/.netrc

script:
  - ./gradlew clean assembleDebug test lint

after_success:
  - node .travis.docs.js
